export const {
  VITE_API_HOST,
  VITE_API_HOST2,
  VITE_HOST,
  VITE_DOWNLOAD_HOST,

  VITE_AREA_DEVELOPER_ID,
  VITE_DEPARTMENT_DEVELOPER_ID,
  VITE_JOB_DEVELOPER_ID,
  VITE_ROLE_DEVELOPER_ID,
  VITE_PRIVILEGE_DEVELOPER,

  VITE_CLOUDINARY_CLOUD_NAME,
  VITE_CLOUDINARY_UPLOAD_PRESET,

  VITE_REVERB_APP_ID,
  VITE_REVERB_APP_KEY,
  VITE_REVERB_APP_SECRET,
  VITE_REVERB_HOST,
  VITE_REVERB_PORT,
  VITE_REVERB_SCHEME,

  VITE_APIRENIEC_HOST,
  VITE_APIRENIEC_TOKEN,
  VITE_TIME_FEACTURE,

  VITE_FIREBASE_API_KEY,
  VITE_FIREBASE_AUTH_DOMAIN,
  VITE_FIREBASE_PROJECT_ID,
  VITE_FIREBASE_STORAGE_BUCKET,
  VITE_FIREBASE_MESSAGING_SENDER_ID,
  VITE_FIREBASE_APP_ID
} = import.meta.env
